WHITESPACE = _{ " " }

atom = _{ dice | number | parens | set }
  number = { ("+" | "-")? ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*) }
  dice = { number? ~ ^"d" ~ number }
  parens = { "(" ~ expr ~ ")" }
  set = { "()" | "(" ~ expr ~ ",)" | "(" ~ expr ~ ("," ~ expr)+ ~ ")" }

binary_operator = _{ add | sub | mul | div }
  add = { "+" }
  sub = { "-" }
  mul = { "*" }
  div = { "/" }

expr = { term ~ (binary_operator ~ term)* }
  term = { atom }

calculation = { SOI ~ expr ~ EOI }